name: Monthly Supabase Backup

on:
  schedule:
    - cron: "0 2 1 * *" # 2 π.μ. UTC κάθε 1η του μήνα
  workflow_dispatch: # Μπορείς να το τρέχεις και χειροκίνητα

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Install PostgreSQL 17 client
        run: |
          echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
          curl -s https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y postgresql-client-17

      - name: Dump Supabase Database
        env:
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
        run: |
          pg_dump \
            --host=${{ secrets.PGHOST }} \
            --port=${{ secrets.PGPORT }} \
            --username=${{ secrets.PGUSER }} \
            --dbname=${{ secrets.PGDATABASE }} \
            --format=custom \
            --file=backup-$(date +'%Y-%m').dump

      # (Προαιρετικό upload – διάλεξε μία από τις παρακάτω επιλογές)

      - name: Upload to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: supabase-backup
          path: backup-*.dump

      # - name: Upload to Supabase storage (π.χ. σε bucket)
      #   run: |
      #     curl -X POST "https://your-project-id.supabase.co/storage/v1/object/${{ secrets.SUPABASE_BACKUP_BUCKET }}/backup-$(date +'%Y-%m').dump" \
      #       -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
      #       -H "Content-Type: application/octet-stream" \
      #       --data-binary @backup-$(date +'%Y-%m').dump
